# Generated by Django 2.1.4 on 2018-12-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=20)),
                ('open_time', models.DateTimeField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('volume', models.FloatField()),
                ('close_time', models.DateTimeField()),
                ('quota_asset_volume', models.FloatField()),
                ('number_of_trades', models.IntegerField()),
                ('taker_buy_base_asset_volume', models.FloatField()),
                ('taker_buy_quote_asset_volume', models.FloatField()),
            ],
        ),
    ]
