# Generated by Django 2.1.4 on 2018-12-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kline',
            name='ignore',
            field=models.FloatField(default=0.0),
        ),
    ]
