# Generated by Django 3.1.6 on 2021-04-07 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('SHORT', 'Short'), ('LONG', 'Long')], max_length=20)),
                ('liquidated', models.BooleanField(default=False)),
                ('start_to_open', models.DateTimeField()),
                ('open_finished', models.DateTimeField()),
                ('liquidate_at', models.DateTimeField()),
                ('start_to_liquidate', models.DateTimeField()),
                ('liquidation_finished', models.DateTimeField()),
                ('open_price', models.FloatField()),
                ('liquidated_price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('initial_fee_balance', models.FloatField()),
                ('after_fee_balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PositionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_message', models.TextField(blank=True, null=True)),
                ('log_json', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='predictive_models.position')),
            ],
        ),
    ]
