# Generated by Django 3.1.6 on 2021-04-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive_models', '0003_auto_20210408_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
