# Generated by Django 3.1.6 on 2021-04-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive_models', '0004_position_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='liq_fee_currency_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='open_fee_currency_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
