# Generated by Django 3.1.6 on 2021-04-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive_models', '0006_auto_20210417_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='fee_tier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
