# Generated by Django 3.1.6 on 2021-05-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xgboost_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('SHORT', 'Short'), ('LONG', 'Long')], max_length=20)),
                ('start_evaluating', models.DateTimeField(blank=True, null=True)),
                ('done_evaluating', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
