# Generated by Django 3.1.6 on 2021-05-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xgboost_models', '0003_auto_20210518_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestrecommendation',
            name='mean_const',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
