# Generated by Django 2.1.4 on 2018-12-25 22:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chronosphere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_percent', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decider_url', models.URLField(max_length=1000)),
                ('decider_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TickRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tick_result', django.contrib.postgres.fields.jsonb.JSONField()),
                ('chronosphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronosphere.Chronosphere')),
            ],
        ),
        migrations.AddField(
            model_name='chronosphere',
            name='decider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronosphere.Decider'),
        ),
    ]
