# Generated by Django 2.1.4 on 2018-12-25 22:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chronosphere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronosphere',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 22, 51, 13, 946088, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
